# Generated by Django 5.1.3 on 2024-11-29 12:08

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_guest_status_wedding_guests_alter_wedding_venue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wedding',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='wedding',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
